# Generated by Django 5.1.2 on 2024-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
