# Generated by Django 5.1.2 on 2024-10-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='history',
        ),
    ]
